# Generated by Django 4.2.1 on 2023-06-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacemanager', '0002_faqdev_rename_faq_faqclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqclient',
            name='position',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='faqdev',
            name='position',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
