# Generated by Django 4.2.1 on 2023-05-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profilemanager', '0011_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('declined', 'Annulé')], default='pending', max_length=100)),
                ('message', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilemanager.company')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilemanager.profile')),
            ],
        ),
    ]
