# Generated by Django 4.2.1 on 2023-05-24 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='meeting_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='meetings',
            name='title',
            field=models.CharField(default='Demande de rendez-vous', max_length=100),
        ),
    ]
