# Generated by Django 4.2.1 on 2023-05-24 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsmanager', '0002_meetings_meeting_date_meetings_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='meeting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('declined', 'Annulé')], default='pending', max_length=10),
        ),
    ]
