# Generated by Django 4.2.1 on 2023-06-05 13:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profilemanager', '0013_merge_20230525_1454'),
        ('meetingsmanager', '0003_alter_meetings_meeting_date_alter_meetings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='title',
            field=models.CharField(default='Vous avez une nouvelle demande de rendez-vous', max_length=100),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilemanager.company')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev', to='profilemanager.profile')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetingsmanager.meetings')),
            ],
        ),
    ]
