# Generated by Django 4.2.1 on 2023-06-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsmanager', '0004_alter_meetings_title_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='content',
        ),
    ]
