# Generated by Django 4.2.1 on 2023-05-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilemanager', '0011_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='used_stacks',
        ),
        migrations.AddField(
            model_name='projects',
            name='used_stacks',
            field=models.ManyToManyField(to='profilemanager.stacks'),
        ),
    ]
