# Generated by Django 4.2.1 on 2023-05-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilemanager', '0012_profile_available'),
        ('profilemanager', '0012_remove_projects_used_stacks_projects_used_stacks'),
    ]

    operations = [
    ]
