# Generated by Django 4.2.1 on 2023-06-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilemanager', '0013_merge_20230525_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stacks',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
