# Generated by Django 4.2.1 on 2023-05-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
