# Generated by Django 4.2.1 on 2023-05-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_display',
            field=models.BooleanField(default=False),
        ),
    ]
