# Generated by Django 4.2.1 on 2023-05-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_phone_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, default='Inconnu', max_length=250),
        ),
    ]
