# Generated by Django 4.2.1 on 2023-05-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.CharField(choices=[('developpeur', 'Développeur'), ('company', 'Entrepreneur')], default='developpeur', max_length=250),
        ),
    ]
